name: kliktoko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <3.29.2"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.5  # Changed from ^4.6.6 to ^4.6.5 for better stability
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  intl: ^0.19.0
  image_picker: ^0.8.8+1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    
